---
name: Bryan M. Maitland
position: "Research Fish Biologist"
address: "USDA Forest Service,\\tabularnewline Rocky Mountain Research Station, Boise, ID, USA"
email: "bmaitland101@gmail.com"
github: bmait101
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::hyndman
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, 
  warning = FALSE, 
  message = FALSE
  )
library(vitae)
library(tidyverse)
source(here::here("R/pretty.R"))
```

# Education

```{r degrees, results='asis'}
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "EPA Postdoctoral Fellow", "2022-2023", "University of Wisconsin-Madison", "Madison, WI, USA",
  "Water Resources Fellow", "2020-2022", "University of Wisconsin-Madison", "Madison, WI, USA",
  "Ph.D. Ecology", "2020", "University of Wyoming", "Laramie, WY, USA",
  "M.Sc. Conservation Biology", "2015", "University of Alberta", "Edmonton, AB, CAN",
  "B.S. Conservation Biology", "2011", "SUNY: ESF", "Syracuse, NY, USA"
  ) |> 
  baretable()

# tribble(
  # ~ Degree, ~ Year, ~ Institution, ~ Where,
  # "EPA Postdoctoral Fellow", "2022-2023", "University of Wisconsin-Madison", "Madison, WI, USA",
  # "Water Resources Postdoctoral Fellow", "2020-2022", "University of Wisconsin-Madison", "Madison, WI, USA",
  # "Ph.D. Ecology", "2020", "University of Wyoming", "Laramie, WY, USA",
  # "M.Sc. Conservation Biology", "2015", "University of Alberta", "Edmonton, AB, CAN",
  # "B.S. Conservation Biology", "2011", "SUNY: ESF", "Syracuse, NY, USA"
# ) %>% 
#   detailed_entries(Degree, Year, Institution, Where)
```

# Employment history

```{r employment, results='asis'}
tribble(
  ~Start, ~End, ~Position,
  2023, 2024, "\\textbf{Research Associate},  Department of Civil and Environmental Engineering, University of Wisconsin-Madison",
  2024, NA, "\\textbf{Research Fish Biologist}, Rocky Mountain Research Station, USDA Forest Service",
) |>
  arrange(-Start) |>
  mutate(
    Start = as.character(Start),
    End = as.character(End),
    End = tidyr::replace_na(End, ""),
    Years = if_else(End == Start,
      as.character(Start),
      paste(Start, "--", End, sep = ""),
      paste(Start, "--", End, sep = "")
    )
  ) |>
  select(Years, Position) |>
  baretable()
```


# Awards and honours

```{r awards, results='asis'}
tribble(
  ~Year, ~Award,
  2024, "Outstanding Service Award, USDA FS Rocky Mountain Research Station",
  2021, "Professional Presentation Award, Wisconsin Chapter American Fisheries Society",
  2019, "Dean’s Graduate Scholar Award, College of Arts and Sciences University of Wyoming",
  2018, "Eugene Maughan Graduate Award, Western Division American Fisheries Society",
  2018, "Hank Gardner Graduate Award, Department of Zoology and Physiology University of Wyoming",
  2017, "Clemens-Rigler Award, Canadian Aquatic Resources Section American Fisheries Society",
  2017, "Board of Visitors Award, College of Arts and Sciences University of Wyoming",
  2017, "Dennis Anderson Fisheries Award, Department Zoology and Physiology University of Wyoming ",
  2017, "William Trachtenberg Scholarship Award, Sustainable Fisheries Foundation",
  2017, "Vern Bressler Fisheries Award, Department of Zoology and Physiology University of Wyoming",
  2015, "Excellence in Fisheries Award, Canadian Aquatic Resources Section American Fisheries Society",
  2015, "Clemens-Rigler Award, Canadian Aquatic Resources Section American Fisheries Society"
  ) |>
  baretable()
```

# Grants

## Awarded

```{r}
grants <- read_csv(here::here("data/grant_income.csv"))

sumgrants <- grants |> 
  filter(Status %in% c("Complete", "In progress")) |> 
  pull(Amount) |> 
  sum(na.rm = TRUE)
```

I have acquired `r scales::dollar_format()(sumgrants)` in research grants since 2015.\vspace*{0.2cm}\enlargethispage*{0.5cm}

```{r grantstable, results='asis'}
grants |>
  # filter(Amount > 100000, Type == "Research") |>
  filter(Status %in% c("Complete", "In progress", "Pending")) |> 
  mutate(
    Time = paste0(Start, ifelse(is.na(End), "", paste0("--", End))),
    Entry = paste(People, ". ``", Title, "''. ",
      "\\emph{Funding from ", Source, "}",
      sep = ""
    ),
    Amount = dollars(Amount)
  ) |>
  arrange(desc(Time), desc(Amount)) |>
  select(Time, Entry, Amount) %>%
  baretable(
    align = "llp{13.3cm}r",
    hline.after = c(0, NROW(.)),
    size = "\\fontsize{10}{12}",
    add.to.row = list(
      pos = as.list(seq(NROW(.))),
      command = rep("\\\\[-0.32cm]", NROW(.))
    )
  )
```

\vspace*{0.2cm}\enlargethispage*{0.5cm} 

## Invited, not awarded

Below are invited full proposals that were not awarded: \vspace*{0.2cm}\enlargethispage*{0.5cm}

```{r grantstable-invite, results='asis'}
grants |>
  filter(!Status %in% c("Complete", "In progress", "Pending")) |> 
  mutate(
    Time = paste0(Start, ifelse(is.na(End), "", paste0("--", End))),
    Entry = paste(People, ". ``", Title, "''. ",
      "\\emph{Funding from ", Source, "}",
      sep = ""
    ),
    Amount = dollars(Amount)
  ) |>
  arrange(desc(Time), desc(Amount)) |>
  select(Time, Entry, Amount) %>%
  baretable(
    align = "llp{13.3cm}r",
    hline.after = c(0, NROW(.)),
    size = "\\fontsize{10}{12}",
    add.to.row = list(
      pos = as.list(seq(NROW(.))),
      command = rep("\\\\[-0.32cm]", NROW(.))
    )
  )
```


# Publications

```{r}
# knitr::write_bib(c("hatchR"), "packages.bib")

bibliography_entries("Rpackages.bib") %>%
  arrange(desc(author$family), issued)
```


```{r map-plot, eval=FALSE, fig.align='center', fig.width=6.1, fig.height=2.25, fig.showtext=TRUE, fig.dpi=300}
load.fontawesome()
home = fontawesome('fa-home')
uni = fontawesome('fa-university')
work = fontawesome('fa-briefcase')
# teach = fontawesome('fa-chalkboard')

world = rnaturalearth::ne_countries("medium", country = "united states of america", returnclass = 'sf')

# Sample data frame with decimal degree coordinates
df <- data.frame(
  longitude = c(-73.935242, -76.144423, -113.4938),
  latitude = c(40.730610, 43.046899, 53.5461),
  name = c("New York", "Syracuse", "Ann Arbor")
)

# Create the sf object
sf_object <- st_as_sf(df, coords = c("longitude", "latitude"), crs = 4326)
ggplot() + 
  geom_sf(data = world, fill = "lightblue", color = "white") +
  geom_sf(data = sf_object, aes(color = name), size = 3) 

cities_geom = st_sfc(
    st_point(c(40.730610,-73.935242)),
    st_point(c(43.046899,-76.144423)),
    st_point(c(53.5461,-113.4938)), 
    crs = 4326
  ) 

cities = st_sf(
  name = c(
    'New York NY, USA',
    'Syracuse NY, USA',
    'Ann Arbor, MI, USA'
    ),
  geometry = cities_geom
  ) |>
  # st_set_crs(4326) |>
  mutate(
    label = c(
      paste(home),
      rep(uni,1),
      paste(work,uni, sep = " "))
  )

ggplot() +
  geom_sf(data = world, color = 'white', lwd = 0.1) +
  geom_sf_text(
    data = cities,
    aes(label = label),
    size = 3,
    color = '#009ACD',
    family = "fontawesome-webfont"
  ) +
  coord_sf(
    crs = '+proj=vandg',
    xlim = c(-14000000, 7000000),
    ylim = c(-750000,8000000)
  )

routes = cities |> 
  as_sfnetwork() |> 
  st_as_sf('edges') |> 
  st_segmentize(units::set_units(1000, m))

ggplot() +
  geom_sf(data = world, color = 'white', lwd = 0.1) +
  geom_sf_text(
    data = cities,
    aes(label = label),
    size = 3,
    color = '#009ACD',
    family = "fontawesome-webfont"
  ) +
  geom_sf(
    data = routes,
    color = '#009ACD',
    size = 1, alpha = 0.5,
    linetype = 21
  ) +
  coord_sf(
    crs = '+proj=vandg',
    xlim = c(-14000000, 7000000),
    ylim = c(-750000,8000000)
  ) +
  theme_void() +
  theme(
    plot.margin = margin(-1, 0, -0.8, 0, "cm")
  )
```